compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16
deepspeed_config:
  deepspeed_config_file: configs/deepspeed/ds_zero2_single.json

num_machines: 1
machine_rank: 0
num_processes: 1
gpu_ids: 0

main_training_function: main
use_cpu: false
debug: false
rdzv_backend: static
main_process_ip: null
main_process_port: 29500
